version: "3.3"


services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbase
    ports:
      - "5432:5432"
    volumes:
      - ~/sql-data/:/var/lib/postgresql/data

