

name: 'Terraform'

on:
  push:
    branches: [ "infra" ]
  pull_request:

permissions:
  id-token: write
  contents: read
jobs:


  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    



    defaults:
      run:
        shell: bash

    steps:
    # Checkout del repositorio
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0 
        TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
    # Login en Azure
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

   # Ejecuto Script de automatizacion
    - name: Terraform install
      run: ./script.sh
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      

